name: ci-npm-generic
on:
  push:
    branches:
    - '**'
    paths-ignore:
    - .github/workflows/**
    - '**.md'
  workflow_dispatch:
  create:
jobs:
  ci:
    uses: 
      Toyota-Motor-North-America/chofer-actions/.github/workflows/ci-npm-generic.yml@v1
    secrets: inherit
